Repository ThisisGenuine/Publicia, pull requests merged in 2022-10, with the labels that each got.

#1 1st commit
  essence.html
Labels: good first issue, ACCEPTED, hacktoberfest-accepted

#3 yt6
  olom.html
Labels: ACCEPTED, hacktoberfest-accepted

#2 col2
  colard.html
Labels: ACCEPTED, hacktoberfest-accepted

#5 Create iop.html
  iop.html
Labels: good first issue, ACCEPTED

#6 portfolio
  portfolio.html
Labels: hacktoberfest-accepted

#8 Create hogg.html
  hogg.html
Labels: hacktoberfest-accepted
